graph TD
  src_model_api.js_Api.fetchIsWebToMpRedirectEnable --> src_utils_Log.success
  src_model_api.js_Api.fetchIsWebToMpRedirectEnable --> src_utils_Log.failure
  src_model_api.js_Api.getUrlScheme --> src_utils_Log.success
  src_model_api.js_Api.getUrlScheme --> src_utils_Log.failure
  src_model_api.js_createEasyFile --> src_model_api.js_Api.useMid
  src_model_api.js_createEasyFile --> src_utils_Log.success
  src_model_api.js_createEasyFile --> src_utils_Log.failure
  src_model_api.js_isEasyFileKeyExist --> src_utils_Log.success
  src_model_api.js_isEasyFileKeyExist --> src_utils_Log.failure
  src_model_api.js_generateRandomUniqueHex --> src_model_api.js_generateRandomHex
  src_model_api.js_generateRandomUniqueHex --> src_model_api.js_isEasyFileKeyExist
  src_model_api.js_Api.getEasyFile --> src_utils_Log.success
  src_model_api.js_Api.getEasyFile --> src_utils_Log.failure
  src_model_api.js_upload_s3 --> src_model_s3.js_uploadFile
  src_model_api.js_upload_s3 --> src_model_api.js_createEasyFile
  src_model_api.js_upload_kodo --> src_model_kodo.js_uploadFile
  src_model_api.js_upload_kodo --> src_model_api.js_createEasyFile
  src_model_api_Api.uploadFile --> src_model_api.js_generateRandomUniqueHex
  src_model_api_Api.uploadFile --> src_utils_Log.success
  src_model_api_Api.uploadFile --> src_model_tracking.js_Tracking.send
  src_model_api_Api.uploadFile --> src_model_s3.js_uploadFile
  src_model_api_Api.uploadFile --> src_model_api.js_createEasyFile
  src_model_api_Api.uploadFile --> src_model_kodo.js_uploadFile
  src_model_api_Api.uploadFile --> src_model_api.js_upload_s3
  src_model_api_Api.uploadFile --> src_model_api.js_upload_kodo
  src_model_api_Api.uploadFile --> src_utils_Log.failure
  src_model_api.js_Api.useMid --> src_utils_Log.success
  src_model_api.js_Api.useMid --> src_utils_Log.failure
  src_model_kodo.js_uploadFile --> src_model_kodo.js_getUploadToken
  src_model_kodo.js_uploadFile --> src_utils_index.js_Log.failure
  src_model_kodo.js_uploadFile --> src_utils_index.js_Log.success
  src_model_kodo.js_getUploadToken --> src_utils_index.js_Log.success
  src_model_kodo.js_getUploadToken --> src_utils_index.js_Log.failure
  src_model_kodo.js_Kodo.getCdnUrl --> src_utils_index.js_Log.success
  src_model_kodo.js_Kodo.getCdnUrl --> src_utils_index.js_Log.failure
  src_model_oss.js_uploadFileByOss --> src_utils_Log.success
  src_model_oss.js_uploadFileByOss --> src_utils_Log.failure
  src_model_s3.js_multipartUploadFile --> src_utils_ReadFile.readFileAsync
  src_model_s3.js_uploadFile --> src_model_s3.js_multipartUploadFile
  src_model_s3.js_uploadFile --> src_model_s3.js_changeFileACL2Public
  src_model_s3.js_uploadFile --> src_model_s3.js_getOssUrl
  src_model_session.js_getSessionId --> src_model_session.js_generateSessionId
  src_model_tracking.js_Tracking.send --> src_model_tracking.js_url
  src_model_tracking.js_Tracking.send --> src_model_tracking.js_referrer
  src_model_tracking.js_Tracking.send --> src_model_tracking.js_Tracking.platform
  src_model_tracking.js_Tracking.send --> src_model_tracking.js_userAgent
  src_model_tracking.js_Tracking.send --> src_model_api.js_Api.useMid
  src_model_tracking.js_Tracking.send --> src_model_tracking.js_timestamp
  src_model_tracking.js_Tracking.send --> src_model_tracking.js_session
  src_model_tracking.js_Tracking.send --> src_utils_Log.failure
  src_model_tracking.js_session --> src_model_session.js_getSessionId
  src_store_global.js_fetchWebToMpRedirectEnable --> src_model_api.js_Api.fetchIsWebToMpRedirectEnable
  src_store_index.js_useProvider --> src_model_api.js_Api.useMid
  src_viewmodels_FileVM.js_getEasyFile --> src_model_api.js_Api.getEasyFile
  src_viewmodels_FileVM.js_getEasyFile --> src_model_kodo.js_Kodo.getCdnUrl
  src_viewmodels_FileVM.js_downloadFile --> src_viewmodels_FileVM.js_isInWeChat
  src_viewmodels_FileVM.js_openMiniProgram --> src_model_api.js_Api.getUrlScheme
  src_viewmodels_FileVM.js_openMiniProgram --> src_model_api.js_Api.useMid
  src_viewmodels_HomeVM.js_getResource --> src_model_kodo.js_Kodo.getCdnUrl
  src_viewmodels_HomeVM.js_uploadFile --> src_model_api_Api.uploadFile
  src_viewmodels_HomeVM.js_uploadFileList --> src_viewmodels_HomeVM.js_uploadFile
  src_viewmodels_HomeVM.js_downloadQRCode --> src_viewmodels_HomeVM.js_generateQRCode
  src_viewmodels_HomeVM.js_downloadAllQRCode --> src_viewmodels_HomeVM.js_generateQRCode
  src_viewmodels_HomeVM.js_downloadAllQRCode --> src_viewmodels_HomeVM.js_createZipFile
  src_viewmodels_HomeVM.js_downloadAllQRCode --> src_viewmodels_HomeVM.js_createDownloadLink
  src_viewmodels_HomeVM.js_generateMpQRCode --> src_model_api_Api.getUnlimitedQRCode
  src_viewmodels_HomeVM.js_generateMpQRCode --> src_viewmodels_HomeVM.js_addHyphenAndSpace
  src_viewmodels_HomeVM.js_generateQRCode --> src_viewmodels_HomeVM.js_generateWebQRCode
  src_viewmodels_HomeVM.js_generateWebQRCode --> src_viewmodels_HomeVM.js_addHyphenAndSpace
  src_viewmodels_HomeVM.js_createDownloadLink --> src_viewmodels_HomeVM.js_addHyphenAndSpace
  src_views_file_FileView.vue_clickOpenMiniprogramBtn --> src_model_tracking.js_Tracking.send
  src_views_file_FileView.vue_clickOpenMiniprogramBtn --> src_viewmodels_index_FileVM.openMiniProgram
  src_views_file_FileView.vue_clickDownloadFile --> src_model_tracking.js_Tracking.send
  src_views_file_FileView.vue_clickDownloadFile --> src_viewmodels_index_FileVM.downloadFile
  src_views_file_FileView.vue_mounted --> src_model_tracking.js_Tracking.platform
  src_views_file_FileView.vue_mounted --> src_viewmodels_index_HomeVM.getResource
  src_views_file_FileView.vue_mounted --> src_viewmodels_index_FileVM.isDownloadRequest
  src_views_file_FileView.vue_mounted --> src_model_tracking.js_Tracking.send
  src_views_file_FileView.vue_mounted --> src_viewmodels_index_FileVM.openMiniProgram
  src_views_home_HomeView.vue_clickAddFileButton --> src_model_tracking.js_Tracking.send
  src_views_home_HomeView.vue_inputFileChanged --> src_model_tracking.js_Tracking.send
  src_views_home_HomeView.vue_inputFileChanged --> src_viewmodels_index_HomeVM.uploadFileList
  src_views_home_HomeView.vue_mounted --> src_viewmodels_index_HomeVM.getResource
  src_views_home_HomeView.vue_mounted --> src_model_tracking.js_Tracking.send
  src_views_home_components_LinkItem.vue_clickUrl --> src_model_tracking.js_Tracking.send
  src_views_home_components_LinkItem.vue_clickCopyUrl --> src_model_tracking.js_Tracking.send
  src_views_home_components_LinkItem.vue_clickCopyUrl --> src_viewmodels_HomeVM_HomeVM.copyUrl
  src_views_home_components_LinkItem.vue_clickDownloadQRCode --> src_model_tracking.js_Tracking.send
  src_views_home_components_LinkItem.vue_clickDownloadQRCode --> src_viewmodels_HomeVM_HomeVM.downloadQRCode
  src_views_home_components_LinkListDialog.vue_closeDialog --> src_model_tracking.js_Tracking.send
  src_views_home_components_LinkListDialog.vue_closeDialog --> src_viewmodels_HomeVM_HomeVM.closeLinkListDialog
  src_views_home_components_LinkListDialog.vue_copyAllUrl --> src_model_tracking.js_Tracking.send
  src_views_home_components_LinkListDialog.vue_copyAllUrl --> src_viewmodels_HomeVM_HomeVM.copyAllUrl
  src_views_home_components_LinkListDialog.vue_downloadAllQRCode --> src_model_tracking.js_Tracking.send
  src_views_home_components_LinkListDialog.vue_downloadAllQRCode --> src_viewmodels_HomeVM_HomeVM.downloadAllQRCode