graph TD
  C:\Code\web\easylink.cc\src\model\api.js_Api.fetchIsWebToMpRedirectEnable --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\api.js_Api.fetchIsWebToMpRedirectEnable --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\api.js_Api.getUrlScheme --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\api.js_Api.getUrlScheme --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\api.js_createEasyFile --> C:\Code\web\easylink.cc\src\model\api.js_Api.useMid
  C:\Code\web\easylink.cc\src\model\api.js_createEasyFile --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\api.js_createEasyFile --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\api.js_isEasyFileKeyExist --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\api.js_isEasyFileKeyExist --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\api.js_generateRandomUniqueHex --> C:\Code\web\easylink.cc\src\model\api.js_generateRandomHex
  C:\Code\web\easylink.cc\src\model\api.js_generateRandomUniqueHex --> C:\Code\web\easylink.cc\src\model\api.js_isEasyFileKeyExist
  C:\Code\web\easylink.cc\src\model\api.js_Api.getEasyFile --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\api.js_Api.getEasyFile --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\api.js_upload_s3 --> C:\Code\web\easylink.cc\src\model\s3.js_uploadFile
  C:\Code\web\easylink.cc\src\model\api.js_upload_s3 --> C:\Code\web\easylink.cc\src\model\api.js_createEasyFile
  C:\Code\web\easylink.cc\src\model\api.js_upload_kodo --> C:\Code\web\easylink.cc\src\model\kodo.js_uploadFile
  C:\Code\web\easylink.cc\src\model\api.js_upload_kodo --> C:\Code\web\easylink.cc\src\model\api.js_createEasyFile
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\model\api.js_generateRandomUniqueHex
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\model\s3.js_uploadFile
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\model\api.js_createEasyFile
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\model\kodo.js_uploadFile
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\model\api.js_upload_s3
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\model\api.js_upload_kodo
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\api.js_Api.useMid --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\api.js_Api.useMid --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\kodo.js_uploadFile --> C:\Code\web\easylink.cc\src\model\kodo.js_getUploadToken
  C:\Code\web\easylink.cc\src\model\kodo.js_uploadFile --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\kodo.js_uploadFile --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\kodo.js_getUploadToken --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\kodo.js_getUploadToken --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\kodo.js_Kodo.getCdnUrl --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\kodo.js_Kodo.getCdnUrl --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\oss.js_uploadFileByOss --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\oss.js_uploadFileByOss --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\s3.js_multipartUploadFile --> C:\Code\web\easylink.cc\src\utils_ReadFile.readFileAsync
  C:\Code\web\easylink.cc\src\model\s3.js_uploadFile --> C:\Code\web\easylink.cc\src\model\s3.js_multipartUploadFile
  C:\Code\web\easylink.cc\src\model\s3.js_uploadFile --> C:\Code\web\easylink.cc\src\model\s3.js_changeFileACL2Public
  C:\Code\web\easylink.cc\src\model\s3.js_uploadFile --> C:\Code\web\easylink.cc\src\model\s3.js_getOssUrl
  C:\Code\web\easylink.cc\src\model\session.js_getSessionId --> C:\Code\web\easylink.cc\src\model\session.js_generateSessionId
  C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send --> C:\Code\web\easylink.cc\src\model\tracking.js_url
  C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send --> C:\Code\web\easylink.cc\src\model\tracking.js_referrer
  C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.platform
  C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send --> C:\Code\web\easylink.cc\src\model\tracking.js_userAgent
  C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send --> C:\Code\web\easylink.cc\src\model\api.js_Api.useMid
  C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send --> C:\Code\web\easylink.cc\src\model\tracking.js_timestamp
  C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send --> C:\Code\web\easylink.cc\src\model\tracking.js_session
  C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\tracking.js_session --> C:\Code\web\easylink.cc\src\model\session.js_getSessionId
  C:\Code\web\easylink.cc\src\store\global.js_fetchWebToMpRedirectEnable --> C:\Code\web\easylink.cc\src\model\api.js_Api.fetchIsWebToMpRedirectEnable
  C:\Code\web\easylink.cc\src\store\index.js_useProvider --> C:\Code\web\easylink.cc\src\model\api.js_Api.useMid
  C:\Code\web\easylink.cc\src\viewmodels\FileVM.js_getEasyFile --> C:\Code\web\easylink.cc\src\model\api.js_Api.getEasyFile
  C:\Code\web\easylink.cc\src\viewmodels\FileVM.js_getEasyFile --> C:\Code\web\easylink.cc\src\model\kodo.js_Kodo.getCdnUrl
  C:\Code\web\easylink.cc\src\viewmodels\FileVM.js_downloadFile --> C:\Code\web\easylink.cc\src\viewmodels\FileVM.js_isInWeChat
  C:\Code\web\easylink.cc\src\viewmodels\FileVM.js_openMiniProgram --> C:\Code\web\easylink.cc\src\model\api.js_Api.getUrlScheme
  C:\Code\web\easylink.cc\src\viewmodels\FileVM.js_openMiniProgram --> C:\Code\web\easylink.cc\src\model\api.js_Api.useMid
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_getResource --> C:\Code\web\easylink.cc\src\model\kodo.js_Kodo.getCdnUrl
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_uploadFile --> C:\Code\web\easylink.cc\src\model\api_Api.uploadFile
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_uploadFileList --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_uploadFile
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_downloadQRCode --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_generateQRCode
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_downloadAllQRCode --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_generateQRCode
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_downloadAllQRCode --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_createZipFile
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_downloadAllQRCode --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_createDownloadLink
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_generateMpQRCode --> C:\Code\web\easylink.cc\src\model\api_Api.getUnlimitedQRCode
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_generateMpQRCode --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_addHyphenAndSpace
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_generateQRCode --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_generateWebQRCode
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_generateWebQRCode --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_addHyphenAndSpace
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_createDownloadLink --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_addHyphenAndSpace
  C:\Code\web\easylink.cc\src\views\file\FileView.vue_clickOpenMiniprogramBtn --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\file\FileView.vue_clickOpenMiniprogramBtn --> C:\Code\web\easylink.cc\src\viewmodels\index_FileVM.openMiniProgram
  C:\Code\web\easylink.cc\src\views\file\FileView.vue_clickDownloadFile --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\file\FileView.vue_clickDownloadFile --> C:\Code\web\easylink.cc\src\viewmodels\index_FileVM.downloadFile
  C:\Code\web\easylink.cc\src\views\file\FileView.vue_mounted --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.platform
  C:\Code\web\easylink.cc\src\views\file\FileView.vue_mounted --> C:\Code\web\easylink.cc\src\viewmodels\index_HomeVM.getResource
  C:\Code\web\easylink.cc\src\views\file\FileView.vue_mounted --> C:\Code\web\easylink.cc\src\viewmodels\index_FileVM.isDownloadRequest
  C:\Code\web\easylink.cc\src\views\file\FileView.vue_mounted --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\file\FileView.vue_mounted --> C:\Code\web\easylink.cc\src\viewmodels\index_FileVM.openMiniProgram
  C:\Code\web\easylink.cc\src\views\home\HomeView.vue_clickAddFileButton --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\home\HomeView.vue_inputFileChanged --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\home\HomeView.vue_inputFileChanged --> C:\Code\web\easylink.cc\src\viewmodels\index_HomeVM.uploadFileList
  C:\Code\web\easylink.cc\src\views\home\HomeView.vue_mounted --> C:\Code\web\easylink.cc\src\viewmodels\index_HomeVM.getResource
  C:\Code\web\easylink.cc\src\views\home\HomeView.vue_mounted --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\home\components\LinkItem.vue_clickUrl --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\home\components\LinkItem.vue_clickCopyUrl --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\home\components\LinkItem.vue_clickCopyUrl --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM_HomeVM.copyUrl
  C:\Code\web\easylink.cc\src\views\home\components\LinkItem.vue_clickDownloadQRCode --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\home\components\LinkItem.vue_clickDownloadQRCode --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM_HomeVM.downloadQRCode
  C:\Code\web\easylink.cc\src\views\home\components\LinkListDialog.vue_closeDialog --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\home\components\LinkListDialog.vue_closeDialog --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM_HomeVM.closeLinkListDialog
  C:\Code\web\easylink.cc\src\views\home\components\LinkListDialog.vue_copyAllUrl --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\home\components\LinkListDialog.vue_copyAllUrl --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM_HomeVM.copyAllUrl
  C:\Code\web\easylink.cc\src\views\home\components\LinkListDialog.vue_downloadAllQRCode --> C:\Code\web\easylink.cc\src\model\tracking.js_Tracking.send
  C:\Code\web\easylink.cc\src\views\home\components\LinkListDialog.vue_downloadAllQRCode --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM_HomeVM.downloadAllQRCode