graph TB
  subgraph 
    middlewares_errorHandler.js_errorHandler --> utils_Log.js_Log.errorHandlerLog
    model_api_lcApi.js_getEasyFiles --> utils_Log.js_Log.success
    model_api_lcApi.js_getEasyFiles --> utils_Log.js_Log.failure
    model_api_lcApi.js_updateEasyfile --> utils_Log.js_Log.success
    model_api_lcApi.js_updateEasyfile --> utils_Log.js_Log.failure
    model_api_qiniuApi.js_generateUploadToken --> model_api_qiniuApi.js_generateUploadPolicy
    model_api_qiniuApi.js_getQiniuCdnData --> utils_Log.js_Log.failure
    model_api_qiniuApi.js_getQiniuCdnData --> utils_Log.js_Log.success
    model_api_qiniuApi.js_getFileStatus --> utils_Log.js_Log.failure
    model_api_qiniuApi.js_getFileStatus --> utils_Log.js_Log.success
    model_api_qiniuApi.js_refreshCdnCache --> model_api_qiniuApi.js_getPrivateObject
    model_api_qiniuApi.js_refreshCdnCache --> utils_Log.js_Log.failure
    model_api_qiniuApi.js_refreshCdnCache --> utils_Log.js_Log.success
    model_api_qiniuApi.js_deleteObject --> utils_Log.js_Log.failure
    model_api_qiniuApi.js_deleteObject --> utils_Log.js_Log.success
    model_api_qiniuApi.js_deleteObject --> model_api_qiniuApi.js_refreshCdnCache
    model_api_qiniuApi.js_getVideoInfo --> model_api_qiniuApi.js_getPrivateObject
    model_api_qiniuApi.js_transcode --> model_api_qiniuApi.js_saveAsName
    model_api_slsApi.js_writeLog --> model_api_slsApi.js_json2contents
    model_api_slsApi.js_writeLog --> utils_Log.js_Log.failure
    model_api_wechatApi.js_getAccessToken --> utils_Log.js_Log.success
    model_api_wechatApi.js_getAccessToken --> utils_Log.js_Log.failure
    model_api_wechatApi.js_generateScheme --> utils_Log.js_Log.success
    model_api_wechatApi.js_generateScheme --> utils_Log.js_Log.failure
    model_api_wechatApi.js_getUnlimitedQRCode --> utils_Log.js_Log.success
    model_api_wechatApi.js_getUnlimitedQRCode --> utils_Log.js_Log.failure
    model_api_wechatApi.js_getPublisherAdposGeneralData --> utils_Log.js_Log.success
    model_api_wechatApi.js_getPublisherAdposGeneralData --> utils_Log.js_Log.failure
    model_api_wechatApi.js_getUserInfo --> utils_Log.js_Log.success
    model_api_wechatApi.js_getUserInfo --> utils_Log.js_Log.failure
    model_db_easyfileDAO.js_insertEasyfile --> config_database.js_pool.query
    model_db_easyfileDAO.js_insertEasyfile --> utils_Log.js_Log.success
    model_db_easyfileDAO.js_insertEasyfile --> utils_Log.js_Log.failure
    model_db_easyfileDAO.js_getEasyfiles --> config_database.js_pool.query
    model_db_easyfileDAO.js_getEasyfiles --> utils_Log.js_Log.success
    model_db_easyfileDAO.js_getEasyfiles --> utils_Log.js_Log.failure
    model_db_easyfileDAO.js_updateEasyfile --> config_database.js_pool.query
    model_db_easyfileDAO.js_updateEasyfile --> utils_Log.js_Log.success
    model_db_easyfileDAO.js_updateEasyfile --> utils_Log.js_Log.failure
    model_db_globalDAO.js_getGlobalValue --> config_database.js_pool.query
    model_db_globalDAO.js_getGlobalValue --> utils_Log.js_Log.success
    model_db_globalDAO.js_getGlobalValue --> utils_Log.js_Log.failure
    model_db_globalDAO.js_setGlobalValue --> config_database.js_pool.query
    model_db_globalDAO.js_setGlobalValue --> utils_Log.js_Log.success
    model_db_globalDAO.js_setGlobalValue --> utils_Log.js_Log.failure
    model_db_machineDAO.js_insertMachine --> config_database.js_pool.query
    model_db_machineDAO.js_insertMachine --> utils_Log.js_Log.success
    model_db_machineDAO.js_insertMachine --> utils_Log.js_Log.failure
    model_db_machineWxUserDAO.js_insertMachineWxUser --> config_database.js_pool.query
    model_db_machineWxUserDAO.js_insertMachineWxUser --> utils_Log.js_Log.success
    model_db_machineWxUserDAO.js_insertMachineWxUser --> utils_Log.js_Log.failure
    model_db_reportDAO.js_insertReport --> config_database.js_pool.query
    model_db_reportDAO.js_insertReport --> utils_Log.js_Log.success
    model_db_reportDAO.js_insertReport --> utils_Log.js_Log.failure
    model_db_wxUserDAO.js_insertWxUser --> config_database.js_pool.query
    model_db_wxUserDAO.js_insertWxUser --> utils_Log.js_Log.success
    model_db_wxUserDAO.js_insertWxUser --> utils_Log.js_Log.failure
    model_db_wxUserDAO.js_findWxUsersByUnionid --> config_database.js_pool.query
    model_db_wxUserDAO.js_findWxUsersByUnionid --> utils_Log.js_Log.success
    model_db_wxUserDAO.js_findWxUsersByUnionid --> utils_Log.js_Log.failure
    services_easyfileService.js_createEasyfile --> model_db_easyfileDAO.js_EasyfileDAO.insertEasyfile
    services_easyfileService.js_createEasyfile --> services_qiniuService.js_QiniuService.runTranscode
    services_easyfileService.js_createEasyfile --> utils_Log.js_Log.success
    services_easyfileService.js_createEasyfile --> utils_Log.js_Log.failure
    services_easyfileService.js_getEasyFiles --> model_db_easyfileDAO.js_EasyfileDAO.getEasyfiles
    services_easyfileService.js_getEasyFiles --> model_api_lcApi.js_LcApi.getEasyFiles
    services_easyfileService.js_getEasyFiles --> utils_Log.js_Log.success
    services_easyfileService.js_getEasyFiles --> utils_Log.js_Log.failure
    services_easyfileService.js_updateEasyfile --> services_easyfileService.js_convertToSnakeCase
    services_easyfileService.js_updateEasyfile --> model_db_easyfileDAO.js_EasyfileDAO.updateEasyfile
    services_easyfileService.js_updateEasyfile --> utils_Log.js_Log.success
    services_easyfileService.js_updateEasyfile --> services_easyfileService.js_convertToCamelCase
    services_easyfileService.js_updateEasyfile --> model_api_lcApi.js_LcApi.updateEasyfile
    services_easyfileService.js_updateEasyfile --> utils_Log.js_Log.failure
    services_machineService.js_createMachine --> model_db_machineDAO.js_MachineDAO.insertMachine
    services_machineService.js_createMachine --> utils_Log.js_Log.success
    services_machineService.js_createMachine --> utils_Log.js_Log.failure
    services_machineWxUserService.js_createMachineWxUser --> model_db_machineWxUserDAO.js_MachineWxUserDAO.insertMachineWxUser
    services_machineWxUserService.js_createMachineWxUser --> utils_Log.js_Log.success
    services_machineWxUserService.js_createMachineWxUser --> utils_Log.js_Log.failure
    services_qiniuService.js_runTranscode --> model_api_slsApi.js_SlsApi.getSlsInstance
    services_qiniuService.js_runTranscode --> model_api_qiniuApi.js_QiniuApi.getVideoInfo
    services_qiniuService.js_runTranscode --> model_api_slsApi.js_SlsApi.writeLog
    services_qiniuService.js_runTranscode --> services_qiniuService.js_needToTranscode
    services_qiniuService.js_runTranscode --> services_easyfileService.js_EasyfileService.updateEasyfile
    services_qiniuService.js_runTranscode --> services_qiniuService.js_getVideoWidthHeight
    services_qiniuService.js_runTranscode --> model_api_qiniuApi.js_QiniuApi.transcode
    services_qiniuService.js_fetchQiniuCdnDataToSls --> model_api_qiniuApi.js_QiniuApi.getQiniuCdnData
    services_qiniuService.js_fetchQiniuCdnDataToSls --> model_api_slsApi.js_SlsApi.getSlsInstance
    services_qiniuService.js_fetchQiniuCdnDataToSls --> model_api_slsApi.js_SlsApi.writeLog
    services_qiniuService.js_fetchQiniuCdnDataToSls --> utils_Log.js_Log.success
    services_qiniuService.js_fetchQiniuCdnDataToSls --> utils_Log.js_Log.failure
    services_qiniuService.js_getUploadToken --> model_api_qiniuApi.js_QiniuApi.generateUploadToken
    services_qiniuService.js_getUploadToken --> utils_Log.js_Log.success
    services_qiniuService.js_getUploadToken --> utils_Log.js_Log.failure
    services_qiniuService.js_review --> services_qiniuService.js_isKodoObjectBanned
    services_qiniuService.js_review --> services_qiniuService.js_banEasyFile
    services_qiniuService.js_review --> model_api_qiniuApi.js_QiniuApi.deleteObject
    services_qiniuService.js_review --> model_api_slsApi.js_SlsApi.getSlsInstance
    services_qiniuService.js_review --> model_api_slsApi.js_SlsApi.writeLog
    services_qiniuService.js_review --> utils_Log.js_Log.success
    services_qiniuService.js_review --> utils_Log.js_Log.failure
    services_qiniuService.js_isKodoObjectBanned --> model_api_qiniuApi.js_QiniuApi.getFileStatus
    services_qiniuService.js_banEasyFile --> services_easyfileService.js_EasyfileService.getEasyFiles
    services_qiniuService.js_banEasyFile --> services_easyfileService.js_EasyfileService.updateEasyfile
    services_qiniuService.js_banEasyFile --> utils_Log.js_Log.failure
    services_qiniuService.js_handleTranscodeNotify --> model_api_slsApi.js_SlsApi.getSlsInstance
    services_qiniuService.js_handleTranscodeNotify --> model_api_qiniuApi.js_QiniuApi.deleteObject
    services_qiniuService.js_handleTranscodeNotify --> services_easyfileService.js_EasyfileService.updateEasyfile
    services_qiniuService.js_handleTranscodeNotify --> model_api_qiniuApi.js_QiniuApi.getVideoInfo
    services_qiniuService.js_handleTranscodeNotify --> model_api_slsApi.js_SlsApi.writeLog
    services_qiniuService.js_getPrivateObjectUrl --> model_api_qiniuApi.js_QiniuApi.getPrivateObject
    services_qiniuService.js_getPrivateObjectUrl --> services_qiniuService.js_review
    services_qiniuService.js_getPrivateObjectUrl --> services_qiniuService.js_isTranscodedKey
    services_qiniuService.js_getPrivateObjectUrl --> services_easyfileService.js_EasyfileService.getEasyFiles
    services_qiniuService.js_getPrivateObjectUrl --> services_qiniuService.js_runTranscode
    services_qiniuService.js_getPrivateObjectUrl --> utils_Log.js_Log.failure
    services_reportService.js_createReport --> model_db_reportDAO.js_ReportDAO.insertReport
    services_reportService.js_createReport --> utils_Log.js_Log.success
    services_reportService.js_createReport --> utils_Log.js_Log.failure
    services_wechatService.js_fetchMpUrlSchemeAndStore --> model_db_globalDAO.js_GlobalDAO.getGlobalValue
    services_wechatService.js_fetchMpUrlSchemeAndStore --> model_api_wechatApi.js_WechatApi.generateScheme
    services_wechatService.js_fetchMpUrlSchemeAndStore --> model_db_globalDAO.js_GlobalDAO.setGlobalValue
    services_wechatService.js_fetchMpUrlSchemeAndStore --> utils_Log.js_Log.success
    services_wechatService.js_fetchMpUrlSchemeAndStore --> utils_Log.js_Log.failure
    services_wechatService.js_getMpRedirectSwitchFromStore --> model_db_globalDAO.js_GlobalDAO.getGlobalValue
    services_wechatService.js_getMpRedirectSwitchFromStore --> utils_Log.js_Log.success
    services_wechatService.js_getMpRedirectSwitchFromStore --> utils_Log.js_Log.failure
    services_wechatService.js_getMpUrlSchemeFromStore --> model_db_globalDAO.js_GlobalDAO.getGlobalValue
    services_wechatService.js_getMpUrlSchemeFromStore --> utils_Log.js_Log.success
    services_wechatService.js_getMpUrlSchemeFromStore --> utils_Log.js_Log.failure
    services_wechatService.js_getMpAccessTokenFromStore --> model_db_globalDAO.js_GlobalDAO.getGlobalValue
    services_wechatService.js_getMpAccessTokenFromStore --> utils_Log.js_Log.success
    services_wechatService.js_getMpAccessTokenFromStore --> utils_Log.js_Log.failure
    services_wechatService.js_fetchMpAccessTokenAndStore --> model_api_wechatApi.js_WechatApi.getAccessToken
    services_wechatService.js_fetchMpAccessTokenAndStore --> model_db_globalDAO.js_GlobalDAO.setGlobalValue
    services_wechatService.js_fetchMpAccessTokenAndStore --> utils_Log.js_Log.success
    services_wechatService.js_fetchMpAccessTokenAndStore --> utils_Log.js_Log.failure
    services_wechatService.js_getYesterday --> services_wechatService.js_format
    services_wechatService.js_fetchMpAdDataToSls --> services_wechatService.js_getYesterday
    services_wechatService.js_fetchMpAdDataToSls --> model_db_globalDAO.js_GlobalDAO.getGlobalValue
    services_wechatService.js_fetchMpAdDataToSls --> model_api_wechatApi.js_WechatApi.getPublisherAdposGeneralData
    services_wechatService.js_fetchMpAdDataToSls --> model_api_slsApi.js_SlsApi.getSlsInstance
    services_wechatService.js_fetchMpAdDataToSls --> model_api_slsApi.js_SlsApi.writeLog
    services_wechatService.js_fetchMpAdDataToSls --> utils_Log.js_Log.failure
    services_wechatService.js_getUserInfo --> model_api_wechatApi.js_WechatApi.getUserInfo
    services_wechatService.js_getUserInfo --> utils_Log.js_Log.success
    services_wechatService.js_getUserInfo --> utils_Log.js_Log.failure
    services_wechatService.js_createWxUser --> model_db_wxUserDAO.js_WxUserDAO.insertWxUser
    services_wechatService.js_createWxUser --> utils_Log.js_Log.success
    services_wechatService.js_createWxUser --> utils_Log.js_Log.failure
    services_wechatService.js_getWxUsersByUnionid --> model_db_wxUserDAO.js_WxUserDAO.findWxUsersByUnionid
    services_wechatService.js_getWxUsersByUnionid --> utils_Log.js_Log.success
    services_wechatService.js_getWxUsersByUnionid --> utils_Log.js_Log.failure
  end