graph TB
  subgraph 
    src/components/ImageView/ImageView.vue_clickImageLoader --> src/viewmodel/index.js_FileVM.previewImage
    src/components/PdfView/PdfView.vue_openPdfFile --> src/viewmodel/index.js_FileVM.openPdfFile
    src/components/UnSupportedView/UnSupportedView.vue_openFile --> src/viewmodel/index.js_FileVM.saveFile
    src/model/api.js_Api.createReport --> src/model/api.js_Api.getWxUserList
    src/model/api.js_Api.createReport --> src/utils/index.js_Log.success
    src/model/api.js_Api.createReport --> src/utils/index.js_Log.failure
    src/model/api.js_Api.getWxUserList --> src/utils/index.js_Log.success
    src/model/api.js_Api.getWxUserList --> src/utils/index.js_Log.failure
    src/model/api.js_Api.createMachineWxUser --> src/utils/index.js_Log.success
    src/model/api.js_Api.createMachineWxUser --> src/utils/index.js_Log.failure
    src/model/api.js_Api.createWxUser --> src/utils/index.js_Log.success
    src/model/api.js_Api.createWxUser --> src/utils/index.js_Log.failure
    src/model/api.js_Api.getEasyFile --> src/utils/index.js_Log.success
    src/model/api.js_Api.getEasyFile --> src/utils/index.js_Log.failure
    src/model/api.js_Api.isEasyFileExist --> src/utils/index.js_Log.success
    src/model/api.js_Api.isEasyFileExist --> src/utils/index.js_Log.failure
    src/model/api.js_Api.getUserInfo --> src/utils/index.js_Log.success
    src/model/api.js_Api.getUserInfo --> src/utils/index.js_Log.failure
    src/model/kodo.js_Kodo.getCdnUrl --> src/utils/index.js_Log.success
    src/model/kodo.js_Kodo.getCdnUrl --> src/utils/index.js_Log.failure
    src/model/tracking.js_Tracking.send --> src/model/tracking.js_useMid
    src/model/tracking.js_Tracking.send --> src/model/tracking.js_Tracking.useUserInfo
    src/model/tracking.js_Tracking.send --> src/model/tracking.js_useSessionId
    src/model/tracking.js_Tracking.send --> src/model/tracking.js_useSubSessionId
    src/model/tracking.js_Tracking.send --> src/model/tracking.js_useSystemInfo
    src/model/tracking.js_Tracking.send --> src/model/tracking.js_useScene
    src/model/tracking.js_Tracking.send --> src/model/tracking.js_Tracking.useRootUnionId
    src/model/tracking.js_Tracking.send --> src/model/tracking.js_Tracking.useShareDepth
    src/model/tracking.js_Tracking.send --> src/model/tracking.js_usePreUnionId
    src/model/tracking.js_useSystemInfo --> src/utils/index.js_File.getStorage
    src/model/tracking.js_useSystemInfo --> src/utils/index.js_File.setStorage
    src/model/tracking.js_Tracking.useShareDepth --> src/utils/index.js_File.getStorage
    src/model/tracking.js_usePreUnionId --> src/utils/index.js_File.getStorage
    src/model/tracking.js_Tracking.useRootUnionId --> src/utils/index.js_File.getStorage
    src/model/tracking.js_Tracking.useRootUnionId --> src/model/tracking.js_Tracking.useUserInfo
    src/model/tracking.js_useScene --> src/utils/index.js_File.getStorage
    src/model/tracking.js_useMid --> src/utils/index.js_File.getStorage
    src/model/tracking.js_useSessionId --> src/utils/index.js_File.getStorage
    src/model/tracking.js_useSubSessionId --> src/utils/index.js_File.getStorage
    src/model/tracking.js_Tracking.useUserInfo --> src/utils/index.js_File.getStorage
    src/model/tracking.js_Tracking.useUserInfo --> src/model/api.js_Api.wxLogin
    src/model/tracking.js_Tracking.useUserInfo --> src/model/api.js_Api.getUserInfo
    src/model/tracking.js_Tracking.useUserInfo --> src/utils/index.js_File.setStorage
    src/model/tracking.js_Tracking.useWxUserId --> src/utils/index.js_File.getStorage
    src/model/tracking.js_Tracking.useWxUserId --> src/model/tracking.js_Tracking.useUserInfo
    src/model/tracking.js_Tracking.useWxUserId --> src/model/api.js_Api.getWxUserList
    src/model/tracking.js_Tracking.useWxUserId --> src/utils/index.js_File.setStorage
    src/model/tracking.js_Tracking.useWxUserId --> src/model/api.js_Api.createWxUser
    src/pages/file/file.vue_trackClickImageView --> src/model/tracking.js_Tracking.send
    src/pages/file/file.vue_trackClickDownloadBtn --> src/model/tracking.js_Tracking.send
    src/pages/file/file.vue_trackClickCopyDownloadBtn --> src/model/tracking.js_Tracking.send
    src/pages/file/file.vue_trackOpenPdf --> src/model/tracking.js_Tracking.send
    src/pages/file/file.vue_clickDownloadBtn --> src/model/tracking.js_Tracking.send
    src/pages/file/file.vue_clickDownloadBtn --> src/pages/file/file.vue_fileType
    src/pages/file/file.vue_clickDownloadBtn --> src/viewmodel/index.js_FileVM.saveFile
    src/pages/file/file.vue_clickEnterFullScreen --> src/model/tracking.js_Tracking.send
    src/pages/file/file.vue_clickEnterFullScreen --> src/viewmodel/index.js_FileVM.previewImage
    src/pages/file/file.vue_clickBackBtn --> src/model/tracking.js_Tracking.send
    src/pages/file/file.vue_clickReportBtn --> src/viewmodel/index.js_FileVM.clickReportBtn
    src/pages/file/file.vue_clickReportBtn --> src/model/tracking.js_Tracking.send
    src/pages/index/index.vue_clickUploadBtn --> src/model/tracking.js_Tracking.send
    src/pages/index/index.vue_clickUploadBtn --> src/viewmodel/index.js_IndexVM.uploadFile
    src/pages/index/index.vue_onFileInputFocus --> src/model/tracking.js_Tracking.send
    src/pages/index/index.vue_clickBackToLastFile --> src/model/tracking.js_Tracking.send
    src/pages/index/index.vue_clickBackToLastFile --> src/viewmodel/index.js_IndexVM.backToCurrentFile
    src/pages/index/index.vue_clickClearCurrentFile --> src/model/tracking.js_Tracking.send
    src/pages/index/index.vue_clickClearCurrentFile --> src/viewmodel/index.js_IndexVM.clearCurrentFile
    src/pages/index/index.vue_onFileInputComfirm --> src/viewmodel/index.js_IndexVM.accessFileFromLink
    src/viewmodel/FileVM.js_clickReportBtn --> src/utils/index.js_UX.showModal
    src/viewmodel/FileVM.js_clickReportBtn --> src/model/api.js_Api.createReport
    src/viewmodel/FileVM.js_clickReportBtn --> src/model/tracking.js_Tracking.useUserInfo
    src/viewmodel/FileVM.js_loadFileToScreen --> src/model/api.js_Api.getEasyFile
    src/viewmodel/FileVM.js_loadFileToScreen --> src/model/kodo.js_Kodo.getCdnUrl
    src/viewmodel/FileVM.js_openPdfFile --> src/utils/index.js_UX.showLoading
    src/viewmodel/FileVM.js_openPdfFile --> src/utils/index.js_File.downloadFile
    src/viewmodel/FileVM.js_openPdfFile --> src/utils/index.js_File.openDocument
    src/viewmodel/FileVM.js_openPdfFile --> src/utils/index.js_UX.hideLoading
    src/viewmodel/FileVM.js_saveFile --> src/utils/index.js_UX.showModal
    src/viewmodel/FileVM.js_saveFile --> src/utils/index.js_UX.showLoading
    src/viewmodel/FileVM.js_saveFile --> src/utils/index.js_UX.setClipboardData
    src/viewmodel/FileVM.js_saveFile --> src/utils/index.js_UX.hideLoading
    src/viewmodel/FileVM.js_saveFile --> src/utils/index.js_UX.showToast
    src/viewmodel/FileVM.js_shareFilePage --> src/model/tracking.js_Tracking.useRootUnionId
    src/viewmodel/FileVM.js_shareFilePage --> src/model/tracking.js_Tracking.useUserInfo
    src/viewmodel/FileVM.js_shareFilePage --> src/model/tracking.js_Tracking.useShareDepth
    src/viewmodel/IndexVM.js_createMachineWxUser --> src/model/tracking.js_Tracking.useWxUserId
    src/viewmodel/IndexVM.js_createMachineWxUser --> src/model/api.js_Api.createMachineWxUser
    src/viewmodel/IndexVM.js_getBackgroundImage --> src/utils/index.js_File.getStorage
    src/viewmodel/IndexVM.js_getBackgroundImage --> src/utils/index.js_File.readFile
    src/viewmodel/IndexVM.js_getBackgroundImage --> src/model/kodo.js_Kodo.getCdnUrl
    src/viewmodel/IndexVM.js_getBackgroundImage --> src/utils/index.js_File.downloadFile
    src/viewmodel/IndexVM.js_getBackgroundImage --> src/utils/index.js_File.saveFile
    src/viewmodel/IndexVM.js_getBackgroundImage --> src/utils/index.js_File.setStorage
    src/viewmodel/IndexVM.js_accessFileFromLink --> src/utils/index.js_UX.showLoading
    src/viewmodel/IndexVM.js_accessFileFromLink --> src/model/api.js_Api.isEasyFileExist
    src/viewmodel/IndexVM.js_accessFileFromLink --> src/utils/index.js_UX.hideLoading
    src/viewmodel/IndexVM.js_accessFileFromLink --> src/model/tracking.js_Tracking.send
    src/viewmodel/IndexVM.js_accessFileFromLink --> src/utils/index.js_UX.showToast
    src/viewmodel/IndexVM.js_uploadFile --> src/utils/index.js_UX.showModal
    src/viewmodel/IndexVM.js_uploadFile --> src/utils/index.js_UX.showLoading
    src/viewmodel/IndexVM.js_uploadFile --> src/utils/index.js_UX.setClipboardData
    src/viewmodel/IndexVM.js_uploadFile --> src/utils/index.js_UX.hideLoading
    src/viewmodel/IndexVM.js_uploadFile --> src/utils/index.js_UX.showToast
    src/viewmodel/IndexVM.js_uploadFile --> src/model/tracking.js_Tracking.send
    src/viewmodel/IndexVM.js_shareIndexPage --> src/model/tracking.js_Tracking.useRootUnionId
    src/viewmodel/IndexVM.js_shareIndexPage --> src/model/tracking.js_Tracking.useUserInfo
    src/viewmodel/IndexVM.js_shareIndexPage --> src/model/tracking.js_Tracking.useShareDepth
  end