graph TD
  src_model_api.js_createEasyFile --> src_model_api.js_Api.useMid
  src_model_api.js_createEasyFile --> src_utils_Log.success
  src_model_api.js_createEasyFile --> src_utils_Log.failure
  src_model_api.js_upload_s3 --> src_model_api.js_createEasyFile
  src_model_api.js_upload_kodo --> src_model_api.js_createEasyFile
  src_model_api_Api.uploadFile --> src_utils_Log.success
  src_model_api_Api.uploadFile --> src_model_api.js_createEasyFile
  src_model_api_Api.uploadFile --> src_model_api.js_upload_s3
  src_model_api_Api.uploadFile --> src_model_api.js_upload_kodo
  src_model_api_Api.uploadFile --> src_utils_Log.failure
  src_model_api.js_Api.useMid --> src_utils_Log.success
  src_model_api.js_Api.useMid --> src_utils_Log.failure
  src_viewmodels_HomeVM.js_uploadFile --> src_model_api_Api.uploadFile
  src_viewmodels_HomeVM.js_uploadFileList --> src_viewmodels_HomeVM.js_uploadFile