graph TD
  src_model_api.js_createEasyFile --> src_model_api.js_useMid
  src_model_api.js_createEasyFile --> src_utils_Log.success
  src_model_api.js_createEasyFile --> src_utils_Log.failure
  src_model_api.js_useMid --> src_utils_Log.success
  src_model_api.js_useMid --> src_utils_Log.success
  src_model_api.js_useMid --> src_utils_Log.success
  src_model_api.js_useMid --> src_utils_Log.failure
  src_model_api.js_upload_s3 --> src_model_s3.js_S3.uploadFile
  src_model_api.js_upload_s3 --> src_model_api.js_createEasyFile
  src_model_api.js_uploadFile --> src_model_api.js_generateRandomUniqueHex
  src_model_api.js_uploadFile --> src_utils_Log.success
  src_model_api.js_uploadFile --> src_model_tracking.js_Tracking.send
  src_model_api.js_uploadFile --> src_model_s3.js_S3.uploadFile
  src_model_api.js_uploadFile --> src_model_api.js_createEasyFile
  src_model_api.js_uploadFile --> src_model_kodo.js_Kodo.uploadFile
  src_model_api.js_uploadFile --> src_model_api.js_createEasyFile
  src_model_api.js_uploadFile --> src_model_api.js_upload_s3
  src_model_api.js_uploadFile --> src_model_api.js_upload_kodo
  src_model_api.js_uploadFile --> src_model_tracking.js_Tracking.send
  src_model_api.js_uploadFile --> src_utils_Log.success
  src_model_api.js_uploadFile --> src_utils_Log.failure
  src_model_api.js_upload_kodo --> src_model_kodo.js_Kodo.uploadFile
  src_model_api.js_upload_kodo --> src_model_api.js_createEasyFile
  src_viewmodels_HomeVM.js_uploadFileList --> src_viewmodels_HomeVM.js_uploadFile