graph TD
  C:\Code\web\easylink.cc\src\model\api.js_createEasyFile --> C:\Code\web\easylink.cc\src\model\api.js_Api.useMid
  C:\Code\web\easylink.cc\src\model\api.js_createEasyFile --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\api.js_createEasyFile --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\api.js_upload_s3 --> C:\Code\web\easylink.cc\src\model\api.js_createEasyFile
  C:\Code\web\easylink.cc\src\model\api.js_upload_kodo --> C:\Code\web\easylink.cc\src\model\api.js_createEasyFile
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\model\api.js_createEasyFile
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\model\api.js_upload_s3
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\model\api.js_upload_kodo
  C:\Code\web\easylink.cc\src\model\api_Api.uploadFile --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\model\api.js_Api.useMid --> C:\Code\web\easylink.cc\src\utils_Log.success
  C:\Code\web\easylink.cc\src\model\api.js_Api.useMid --> C:\Code\web\easylink.cc\src\utils_Log.failure
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_uploadFile --> C:\Code\web\easylink.cc\src\model\api_Api.uploadFile
  C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_uploadFileList --> C:\Code\web\easylink.cc\src\viewmodels\HomeVM.js_uploadFile